FROM mcr.microsoft.com/devcontainers/typescript-node:22

# Puedes agregar dependencias globales adicionales aquí si el proyecto lo requiere
# RUN apt-get update && export DEBIAN_FRONTEND=noninteractive \
#     && apt-get -y install --no-install-recommends <tu-paquete>
