import React, { useEffect, useRef, useState, useId } from "react";
import mermaid from "mermaid";

interface MermaidProps {
  chart: string;
}

export const Mermaid: React.FC<MermaidProps> = ({ chart }) => {
  const containerRef = useRef<HTMLDivElement>(null);
  const [svgContent, setSvgContent] = useState<string>("");

  // Create a unique ID that is valid for HTML id attributes (remove colons generated by useId)
  const baseId = useId().replace(/:/g, "");
  const mermaidId = `mermaid-${baseId}`;

  useEffect(() => {
    let isMounted = true;

    const renderChart = async () => {
      try {
        mermaid.initialize({
          startOnLoad: false,
          theme: "neutral",
          securityLevel: "loose",
        });

        // Render returns an object { svg, bindFunctions }
        const { svg } = await mermaid.render(mermaidId, chart);

        if (isMounted) {
          setSvgContent(svg);
        }
      } catch (error) {
        console.error("Mermaid rendering failed:", error);
        if (isMounted) {
          setSvgContent(
            `<div class="text-red-500 p-4 border border-red-200 bg-red-50 rounded-lg text-sm">Error al renderizar el diagrama Mermaid. Verifica la sintaxis.</div>`,
          );
        }
      }
    };

    if (chart) {
      renderChart();
    }

    return () => {
      isMounted = false;
    };
  }, [chart, mermaidId]);

  return (
    <div
      ref={containerRef}
      className="flex justify-center my-8 p-6 bg-white border border-slate-200 rounded-xl overflow-x-auto shadow-sm"
      dangerouslySetInnerHTML={{
        __html:
          svgContent ||
          '<div class="animate-pulse text-slate-400">Generando diagrama...</div>',
      }}
    />
  );
};
